apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nzd-deployment
  labels: 
    app: nzd
spec:
  selector:
    matchLabels:
      app: nzd
  replicas: 3
  template:
    metadata:
      labels:
        app: nzd
    spec:
      containers:
        - name: nzd
          image:  local/nzd
          imagePullPolicy: Never
          ports:
          - name:  nzd-service
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name:  nzd-service
spec:
  selector:
    app:  nzd
  ports:
  - port:  3000
    targetPort:  nzd-service